import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black`}
    >

    <main className="z-10 ease-in duration-300 px-5 sm:px-8 md:px-10 xl:px-20 bg-white dark:bg-black">
      <NavBar/>
      {children}
    </main>

    </body>
    </html>
  );
}
